[workspace.package]
license = "MIT-0"
authors = ["Parity Technologies <admin@parity.io>"]
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/polkadot-sdk-parachain-template.git"
edition = "2021"

[workspace]
members = [
    "node",
    "pallets/template",
    "runtime",
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.3" }
codec = { version = "3.6.12", default-features = false, package = "parity-scale-codec" }
color-print = { version = "0.3.4" }
cumulus-client-cli = { path = "cumulus/client/cli", default-features = false, version = "0.15.0" }
cumulus-client-collator = { path = "cumulus/client/collator", default-features = false, version = "0.15.0" }
cumulus-client-consensus-aura = { path = "cumulus/client/consensus/aura", default-features = false, version = "0.15.0" }
cumulus-client-consensus-common = { path = "cumulus/client/consensus/common", default-features = false, version = "0.15.0" }
cumulus-client-consensus-proposer = { path = "cumulus/client/consensus/proposer", default-features = false, version = "0.14.0" }
cumulus-client-service = { path = "cumulus/client/service", default-features = false, version = "0.15.0" }
cumulus-primitives-core = { path = "cumulus/primitives/core", default-features = false, version = "0.14.0" }
cumulus-primitives-parachain-inherent = { path = "cumulus/primitives/parachain-inherent", default-features = false, version = "0.14.0" }
cumulus-relay-chain-interface = { path = "cumulus/client/relay-chain-interface", default-features = false, version = "0.15.0" }
docify = { version = "0.2.8" }
frame-benchmarking = { path = "substrate/frame/benchmarking", default-features = false, version = "36.0.0" }
frame-benchmarking-cli = { path = "substrate/utils/frame/benchmarking-cli", default-features = false, version = "40.0.0" }
futures = { version = "0.3.30" }
jsonrpsee = { version = "0.23.2" }
log = { version = "0.4.21", default-features = false }
pallet-transaction-payment-rpc = { path = "substrate/frame/transaction-payment/rpc", default-features = false, version = "38.0.0" }
parachain-template-runtime = { path = "templates/parachain/runtime", version = "0.1.0" }
polkadot-cli = { path = "polkadot/cli", default-features = false, version = "15.0.0" }
polkadot-primitives = { path = "polkadot/primitives", default-features = false, version = "14.0.0" }
prometheus-endpoint = { path = "substrate/utils/prometheus", default-features = false, package = "substrate-prometheus-endpoint", version = "0.17.0" }
sc-basic-authorship = { path = "substrate/client/basic-authorship", default-features = false, version = "0.42.0" }
sc-chain-spec = { path = "substrate/client/chain-spec", default-features = false, version = "35.0.0" }
sc-cli = { path = "substrate/client/cli", default-features = false, version = "0.44.0" }
sc-client-api = { path = "substrate/client/api", default-features = false, version = "35.1.0" }
sc-consensus = { path = "substrate/client/consensus/common", default-features = false, version = "0.41.0" }
sc-executor = { path = "substrate/client/executor", default-features = false, version = "0.39.0" }
sc-network = { path = "substrate/client/network", default-features = false, version = "0.42.0" }
sc-network-sync = { path = "substrate/client/network/sync", default-features = false, version = "0.41.0" }
sc-offchain = { path = "substrate/client/offchain", default-features = false, version = "37.0.0" }
sc-rpc = { path = "substrate/client/rpc", default-features = false, version = "37.0.0" }
sc-service = { path = "substrate/client/service", default-features = false, version = "0.43.0" }
sc-sysinfo = { path = "substrate/client/sysinfo", default-features = false, version = "35.0.0" }
sc-telemetry = { path = "substrate/client/telemetry", default-features = false, version = "22.0.0" }
sc-tracing = { path = "substrate/client/tracing", default-features = false, version = "35.0.0" }
sc-transaction-pool = { path = "substrate/client/transaction-pool", default-features = false, version = "35.0.0" }
sc-transaction-pool-api = { path = "substrate/client/transaction-pool/api", default-features = false, version = "35.0.0" }
serde = { version = "1.0.197", default-features = false }
serde_json = { version = "1.0.114", default-features = false }
sp-api = { path = "substrate/primitives/api", default-features = false, version = "33.0.0" }
sp-block-builder = { path = "substrate/primitives/block-builder", default-features = false, version = "33.0.0" }
sp-blockchain = { path = "substrate/primitives/blockchain", default-features = false, version = "35.1.0" }
sp-consensus-aura = { path = "substrate/primitives/consensus/aura", default-features = false, version = "0.39.0" }
sp-core = { path = "substrate/primitives/core", default-features = false, version = "34.0.0" }
sp-io = { path = "substrate/primitives/io", default-features = false, version = "37.0.0" }
sp-keystore = { path = "substrate/primitives/keystore", default-features = false, version = "0.40.0" }
sp-runtime = { path = "substrate/primitives/runtime", default-features = false, version = "38.0.0" }
sp-timestamp = { path = "substrate/primitives/timestamp", default-features = false, version = "33.0.0" }
substrate-frame-rpc-system = { path = "substrate/utils/frame/rpc/system", default-features = false, version = "36.0.0" }
xcm = { path = "polkadot/xcm", default-features = false, package = "staging-xcm", version = "14.0.1" }
substrate-build-script-utils = { path = "substrate/utils/build-script-utils", default-features = false, version = "11.0.0" }
